In [5]:
import pandas as pd
import numpy as np


In [6]:
df=pd.read_csv("Student-Performance-csv_T4qDx.csv")
df

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0                 7               99                        Yes            9   
1                 4               82                         No            4   
2                 8               51                        Yes            7   
3                 5               52                        Yes            5   
4                 7               75                         No            8   
...             ...              ...                        ...          ...   
9995              1               49                        Yes            4   
9996              7               64                        Yes            8   
9997              6               83                        Yes            8   
9998              9               97                        Yes            7   
9999              7               74                         No            8   

      Sample Question Papers Practiced  Performance Index  
0                                    1               91.0  
1                                    2               65.0  
2                                    2               45.0  
3                                    2               36.0  
4                                    5               66.0  
...                                ...                ...  
9995                                 2               23.0  
9996                                 5               58.0  
9997                                 5               74.0  
9998                                 0               95.0  
9999                                 1               64.0  

[10000 rows x 6 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   Hours Studied                     10000 non-null  int64  
 1   Previous Scores                   10000 non-null  int64  
 2   Extracurricular Activities        10000 non-null  object 
 3   Sleep Hours                       10000 non-null  int64  
 4   Sample Question Papers Practiced  10000 non-null  int64  
 5   Performance Index                 10000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 468.9+ KB


In [8]:
df.head()

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0              7               99                        Yes            9   
1              4               82                         No            4   
2              8               51                        Yes            7   
3              5               52                        Yes            5   
4              7               75                         No            8   

   Sample Question Papers Practiced  Performance Index  
0                                 1               91.0  
1                                 2               65.0  
2                                 2               45.0  
3                                 2               36.0  
4                                 5               66.0

In [9]:
df.tail()

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
9995              1               49                        Yes            4   
9996              7               64                        Yes            8   
9997              6               83                        Yes            8   
9998              9               97                        Yes            7   
9999              7               74                         No            8   

      Sample Question Papers Practiced  Performance Index  
9995                                 2               23.0  
9996                                 5               58.0  
9997                                 5               74.0  
9998                                 0               95.0  
9999                                 1               64.0

In [10]:
df.describe()

Hours Studied  Previous Scores   Sleep Hours  \
count   10000.000000     10000.000000  10000.000000   
mean        4.992900        69.445700      6.530600   
std         2.589309        17.343152      1.695863   
min         1.000000        40.000000      4.000000   
25%         3.000000        54.000000      5.000000   
50%         5.000000        69.000000      7.000000   
75%         7.000000        85.000000      8.000000   
max         9.000000        99.000000      9.000000   

       Sample Question Papers Practiced  Performance Index  
count                      10000.000000       10000.000000  
mean                           4.583300          55.224800  
std                            2.867348          19.212558  
min                            0.000000          10.000000  
25%                            2.000000          40.000000  
50%                            5.000000          55.000000  
75%                            7.000000          71.000000  
max                            9.000000         100.000000

In [11]:
df.isnull().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [12]:
df.dtypes

Hours Studied                         int64
Previous Scores                       int64
Extracurricular Activities           object
Sleep Hours                           int64
Sample Question Papers Practiced      int64
Performance Index                   float64
dtype: object

In [13]:
# for changing data types of extra curricular activities 
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [14]:
le=LabelEncoder()
df["Extracurricular Activities"]=le.fit_transform(df["Extracurricular Activities"])

In [15]:
df

Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
0                 7               99                           1            9   
1                 4               82                           0            4   
2                 8               51                           1            7   
3                 5               52                           1            5   
4                 7               75                           0            8   
...             ...              ...                         ...          ...   
9995              1               49                           1            4   
9996              7               64                           1            8   
9997              6               83                           1            8   
9998              9               97                           1            7   
9999              7               74                           0            8   

      Sample Question Papers Practiced  Performance Index  
0                                    1               91.0  
1                                    2               65.0  
2                                    2               45.0  
3                                    2               36.0  
4                                    5               66.0  
...                                ...                ...  
9995                                 2               23.0  
9996                                 5               58.0  
9997                                 5               74.0  
9998                                 0               95.0  
9999                                 1               64.0  

[10000 rows x 6 columns]

In [16]:
#y=m1x1+m2x2+m3x3+m4x4+m5x5+c because we have 5 features 

x=df[["Hours Studied","Previous Scores","Extracurricular Activities","Sleep Hours","Sample Question Papers Practiced"]]
x

Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
0                 7               99                           1            9   
1                 4               82                           0            4   
2                 8               51                           1            7   
3                 5               52                           1            5   
4                 7               75                           0            8   
...             ...              ...                         ...          ...   
9995              1               49                           1            4   
9996              7               64                           1            8   
9997              6               83                           1            8   
9998              9               97                           1            7   
9999              7               74                           0            8   

      Sample Question Papers Practiced  
0                                    1  
1                                    2  
2                                    2  
3                                    2  
4                                    5  
...                                ...  
9995                                 2  
9996                                 5  
9997                                 5  
9998                                 0  
9999                                 1  

[10000 rows x 5 columns]

In [17]:
y=df["Performance Index"]
y

0       91.0
1       65.0
2       45.0
3       36.0
4       66.0
        ... 
9995    23.0
9996    58.0
9997    74.0
9998    95.0
9999    64.0
Name: Performance Index, Length: 10000, dtype: float64

In [18]:
#splitting the data into a training data and testing data 

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2) # automatically training size 80%

x_train

Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
8767              5               93                           1            8   
1266              2               63                           0            7   
3892              3               45                           0            5   
8109              4               93                           0            7   
8789              9               60                           0            5   
...             ...              ...                         ...          ...   
6327              1               71                           0            5   
7434              6               41                           1            5   
6464              9               72                           0            8   
6248              3               40                           0            4   
9288              7               79                           0            5   

      Sample Question Papers Practiced  
8767                                 6  
1266                                 8  
3892                                 5  
8109                                 3  
8789                                 4  
...                                ...  
6327                                 1  
7434                                 8  
6464                                 9  
6248                                 1  
9288                                 9  

[8000 rows x 5 columns]

In [19]:
# to standardizing the data  we are using z scale= x-average/standrad deviation  , with standard scaler library
# optional and it is easy to read the data for the model 
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_train_scaled



array([[-1.11163338e-03,  1.36462914e+00,  1.02020406e+00,
         8.68088691e-01,  4.91872938e-01],
       [-1.16107689e+00, -3.65569304e-01, -9.80196059e-01,
         2.77351235e-01,  1.18888534e+00],
       [-7.74421807e-01, -1.40368837e+00, -9.80196059e-01,
        -9.04123676e-01,  1.43366738e-01],
       ...,
       [ 1.54550871e+00,  1.53490230e-01, -9.80196059e-01,
         8.68088691e-01,  1.53739154e+00],
       [-7.74421807e-01, -1.69205478e+00, -9.80196059e-01,
        -1.49486113e+00, -1.25065806e+00],
       [ 7.72198541e-01,  5.57203200e-01, -9.80196059e-01,
        -9.04123676e-01,  1.53739154e+00]])

In [20]:
x_test_scaled=scaler.fit_transform(x_test)
x_test_scaled

array([[-1.52018325,  0.41075347,  0.97238125, -0.31095522,  0.85294009],
       [-0.75105436, -1.66434123, -1.02840321, -0.89655828,  1.20279246],
       [-0.75105436, -0.3962278 ,  0.97238125, -0.89655828, -0.89632178],
       ...,
       [ 0.40263897, -0.22330325,  0.97238125,  0.86025089,  1.20279246],
       [-0.75105436,  1.6788669 , -1.02840321, -0.89655828, -1.24617416],
       [-0.36648992, -0.972643  ,  0.97238125,  0.27464783, -0.19661703]])

In [21]:
from sklearn.linear_model import LinearRegression
import pickle  # to store model in a physical file 
from sklearn.metrics import mean_squared_error,median_absolute_error, r2_score

In [22]:
# training the model

model=LinearRegression()
model.fit(x_train_scaled,y_train)

LinearRegression()

In [23]:
# testing the model

model.predict(x_test_scaled) # this x_test is nothing but predicted y

array([51.68802721, 19.83318734, 41.6406174 , ..., 55.82850748,
       77.52305656, 35.64149095])

In [28]:
x_test_scaled

array([[-1.52018325,  0.41075347,  0.97238125, -0.31095522,  0.85294009],
       [-0.75105436, -1.66434123, -1.02840321, -0.89655828,  1.20279246],
       [-0.75105436, -0.3962278 ,  0.97238125, -0.89655828, -0.89632178],
       ...,
       [ 0.40263897, -0.22330325,  0.97238125,  0.86025089,  1.20279246],
       [-0.75105436,  1.6788669 , -1.02840321, -0.89655828, -1.24617416],
       [-0.36648992, -0.972643  ,  0.97238125,  0.27464783, -0.19661703]])

In [25]:
# we can also check for single record 

model.predict([[-1.57028968,  1.21427247,  1.05659932,  0.88175854,  0.167927  ]])

# we need to  find the metrics how accurate our model is but as of now we are good 

array([66.12243738])

In [26]:
y_pred=model.predict(x_test_scaled)  # this x_test is nothing but predicted y
y_pred

array([51.68802721, 19.83318734, 41.6406174 , ..., 55.82850748,
       77.52305656, 35.64149095])

In [29]:
mean_squared_error(y_test,y_pred)  # y test is actual y , y_pred is predicted y from x_test 

4.277495566634798

In [30]:
r2_score(y_test,y_pred)

0.9886985286352549

In [32]:
import pickle
with open("Student-Performance.pkl",'wb') as file :
    pickle.dump((model,scaler,le),file)